// Code generated by "genmethods"; DO NOT EDIT.

package sdl

func (window *Window) StartTextInput() bool {
	return StartTextInput(window)
}
func (window *Window) StopTextInput() bool {
	return StopTextInput(window)
}

func (window *Window) WarpMouseInWindow(x float32, y float32) { WarpMouseInWindow(window, x, y) }
func (renderer *Renderer) SetDrawColor(r, g, b, a uint8) bool {
	return SetRenderDrawColor(renderer, r, g, b, a)
}
func (renderer *Renderer) Present() bool {
	return RenderPresent(renderer)
}
func (renderer *Renderer) Clear() bool {
	return RenderClear(renderer)
}
func (renderer *Renderer) Destroy() {
	DestroyRenderer(renderer)
}

func (renderer *Renderer) RenderRect(rect *FRect) bool { return RenderRect(renderer, rect) }

func (renderer *Renderer) RenderFillRect(rect *FRect) bool { return RenderFillRect(renderer, rect) }

func (renderer *Renderer) RenderDebugText(x, y float32, str string) bool {
	return RenderDebugText(renderer, x, y, str)
}

func (renderer *Renderer) CreateTextureFromSurface(surface *Surface) *Texture {
	return CreateTextureFromSurface(renderer, surface)
}

func (renderer *Renderer) RenderTexture(texture *Texture, srcrect *FRect, dstrect *FRect) bool {
	return RenderTexture(renderer, texture, srcrect, dstrect)
}
func (texture *Texture) Destroy() {
	DestroyTexture(texture)
}
func (surface *Surface) Destroy() {
	DestroySurface(surface)
}

func (src *Surface) Blit(srcrect *Rect, dst *Surface, dstrect *Rect) bool {
	return BlitSurface(src, srcrect, dst, dstrect)
}
func (surface *Surface) Lock() bool {
	return LockSurface(surface)
}
func (surface *Surface) Unlock() {
	UnlockSurface(surface)
}
func (window *Window) Destroy() {
	DestroyWindow(window)
}
func (window *Window) GetSurface() *Surface {
	return GetWindowSurface(window)
}
func (window *Window) Hide() bool {
	return HideWindow(window)
}
func (window *Window) Show() bool {
	return ShowWindow(window)
}
func (window *Window) UpdateSurface() bool {
	return UpdateWindowSurface(window)
}
